// Copyright 2024 IOTA Stiftung.
// SPDX-License-Identifier: Apache-2.0.

// This file is generated by scripts/generate-icons.mjs.
// Do not edit it manually.

/* eslint-disable */
import React from "react";
import type { Icon, IconWeight } from "@phosphor-icons/react";
import type { IconsProps } from "../types/iconTypes";

function mapTypeToWeight(type: IconsProps["type"]): IconWeight {
	switch (type) {
		case "fill":
			return "fill";
		case "duotone":
			return "duotone";
		case "bold":
			return "bold";
		case "light":
			return "light";
		case "thin":
			return "thin";
		case "regular":
		default:
			return "regular";
	}
}

export function createPhosphorIcon(displayName: string, Component: Icon): React.FC<IconsProps> {
	const WrappedIcon: React.FC<IconsProps> = ({
		color = "currentColor",
		width = 24,
		height = width,
		className = "",
		type = "regular",
		style,
		...rest
	}) => {
		const resolvedStyle = {
			color,
			fill: color,
			...style
		};

		return (
			<Component
				{...rest}
				weight={mapTypeToWeight(type)}
				color={color}
				width={width}
				height={height}
				className={className}
				style={resolvedStyle}
			/>
		);
	};

	WrappedIcon.displayName = displayName;

	return WrappedIcon;
}

export default createPhosphorIcon;
