// Copyright 2024 IOTA Stiftung.
// SPDX-License-Identifier: Apache-2.0.

// This file is generated by scripts/generate-icons.mjs.
// Do not edit it manually.

/* eslint-disable */
import { File as PhosphorFile } from "@phosphor-icons/react";
import { createPhosphorIcon } from "./createPhosphorIcon";

export const File = createPhosphorIcon("File", PhosphorFile);
