// Copyright 2024 IOTA Stiftung.
// SPDX-License-Identifier: Apache-2.0.

// This file is generated by scripts/generate-icons.mjs.
// Do not edit it manually.

/* eslint-disable */
import { IdentificationCard as PhosphorIdentificationCard } from "@phosphor-icons/react";
import { createPhosphorIcon } from "./createPhosphorIcon";

export const IdentificationCard = createPhosphorIcon("IdentificationCard", PhosphorIdentificationCard);
