// Copyright 2024 IOTA Stiftung.
// SPDX-License-Identifier: Apache-2.0.

// This file is generated by scripts/generate-icons.mjs.
// Do not edit it manually.

/* eslint-disable */
export { ArrowRight } from "./arrowRight";
export { ArrowRightFat } from "./arrowRightFat";
export { Bag } from "./bag";
export { Bell } from "./bell";
export { Briefcase } from "./briefcase";
export { Building } from "./building";
export { CalendarDots } from "./calendarDots";
export { Camera } from "./camera";
export { CaretDown } from "./caretDown";
export { CaretLeft } from "./caretLeft";
export { ChartBar } from "./chartBar";
export { Check } from "./check";
export { CheckCircle } from "./checkCircle";
export { Clipboard } from "./clipboard";
export { Clock } from "./clock";
export { DotsThreeVertical } from "./dotsThreeVertical";
export { Envelope } from "./envelope";
export { Eye } from "./eye";
export { File } from "./file";
export { FileLock } from "./fileLock";
export { FilePdf } from "./filePdf";
export { FileText } from "./fileText";
export { Fingerprint } from "./fingerprint";
export { Fire } from "./fire";
export { Folders } from "./folders";
export { Gear } from "./gear";
export { Globe } from "./globe";
export { House } from "./house";
export { IdentificationCard } from "./identificationCard";
export { Image } from "./image";
export { Info } from "./info";
export { Keyboard } from "./keyboard";
export { Link } from "./link";
export { List } from "./list";
export { Lock } from "./lock";
export { MagnifyingGlass } from "./magnifyingGlass";
export { MapPin } from "./mapPin";
export { Megaphone } from "./megaphone";
export { NotePencil } from "./notePencil";
export { PaperClip } from "./paperClip";
export { PencilLine } from "./pencilLine";
export { Phone } from "./phone";
export { Plus } from "./plus";
export { Question } from "./question";
export { SealCheck } from "./sealCheck";
export { SealPercent } from "./sealPercent";
export { ShieldCheck } from "./shieldCheck";
export { ShieldWarning } from "./shieldWarning";
export { ShoppingCart } from "./shoppingCart";
export { Star } from "./star";
export { Trash } from "./trash";
export { Upload } from "./upload";
export { User } from "./user";
export { UserCircle } from "./userCircle";
export { UserPlus } from "./userPlus";
export { UserRectangle } from "./userRectangle";
export { UsersThree } from "./usersThree";
export { WarningCircle } from "./warningCircle";
export { X } from "./x";
export { XCircle } from "./xCircle";

// Export the props type
export type { IconsProps } from "../types/iconTypes";
