#!/usr/bin/env node
// Copyright 2024 IOTA Stiftung.
// SPDX-License-Identifier: Apache-2.0.

/**
 * Generates icon wrapper components and the icons index file.
 *
 * The generated wrappers:
 * - use `@phosphor-icons/react` as the implementation source
 * - preserve the current TWIN `IconsProps` API
 * - map `type` -> phosphor `weight`
 * - keep per-icon files for tree-shaking and explicit package exports
 *
 * The icon manifest in `src/icons/iconManifest.ts` is the single source of truth.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ICONS_DIR = path.resolve(__dirname, '../src/icons');
const MANIFEST_PATH = path.resolve(ICONS_DIR, 'iconManifest.ts');

const FILE_HEADER = `// Copyright 2024 IOTA Stiftung.
// SPDX-License-Identifier: Apache-2.0.

// This file is generated by scripts/generate-icons.mjs.
// Do not edit it manually.

/* eslint-disable */
`;

function ensureDir(dirPath) {
	fs.mkdirSync(dirPath, { recursive: true });
}

function writeFileIfChanged(filePath, content) {
	const normalized = content.endsWith('\n') ? content : `${content}\n`;

	if (fs.existsSync(filePath)) {
		const current = fs.readFileSync(filePath, 'utf8');
		if (current === normalized) {
			return false;
		}
	}

	fs.writeFileSync(filePath, normalized, 'utf8');
	return true;
}

async function loadManifest() {
	if (!fs.existsSync(MANIFEST_PATH)) {
		throw new Error(`Icon manifest not found: ${MANIFEST_PATH}`);
	}

	const manifestModule = await import(pathToFileURL(MANIFEST_PATH).href);
	const icons = manifestModule.iconManifest;

	if (!Array.isArray(icons)) {
		throw new TypeError('The icon manifest must export an array named `iconManifest`.');
	}

	return icons;
}

function validateIcons(icons) {
	const fileNames = new Set();
	const exportNames = new Set();
	const phosphorNames = new Set();

	for (const icon of icons) {
		if (!icon || typeof icon !== 'object') {
			throw new TypeError('Each icon manifest entry must be an object.');
		}

		const { fileName, exportName, phosphorName } = icon;

		if (
			typeof fileName !== 'string' ||
			typeof exportName !== 'string' ||
			typeof phosphorName !== 'string' ||
			fileName.length === 0 ||
			exportName.length === 0 ||
			phosphorName.length === 0
		) {
			throw new TypeError(
				'Each icon manifest entry must include non-empty `fileName`, `exportName`, and `phosphorName` strings.'
			);
		}

		if (fileNames.has(fileName)) {
			throw new Error(`Duplicate icon fileName detected: ${fileName}`);
		}

		if (exportNames.has(exportName)) {
			throw new Error(`Duplicate icon exportName detected: ${exportName}`);
		}

		if (phosphorNames.has(`${fileName}:${phosphorName}`)) {
			continue;
		}

		fileNames.add(fileName);
		exportNames.add(exportName);
		phosphorNames.add(`${fileName}:${phosphorName}`);
	}
}

function generateHelperFile() {
	return `${FILE_HEADER}import React from "react";
import type { Icon, IconWeight } from "@phosphor-icons/react";
import type { IconsProps } from "../types/iconTypes";

function mapTypeToWeight(type: IconsProps["type"]): IconWeight {
	switch (type) {
		case "fill":
			return "fill";
		case "duotone":
			return "duotone";
		case "bold":
			return "bold";
		case "light":
			return "light";
		case "thin":
			return "thin";
		case "regular":
		default:
			return "regular";
	}
}

export function createPhosphorIcon(displayName: string, Component: Icon): React.FC<IconsProps> {
	const WrappedIcon: React.FC<IconsProps> = ({
		color = "currentColor",
		width = 24,
		height = width,
		className = "",
		type = "regular",
		style,
		...rest
	}) => {
		const resolvedStyle = {
			color,
			fill: color,
			...style
		};

		return (
			<Component
				{...rest}
				weight={mapTypeToWeight(type)}
				color={color}
				width={width}
				height={height}
				className={className}
				style={resolvedStyle}
			/>
		);
	};

	WrappedIcon.displayName = displayName;

	return WrappedIcon;
}

export default createPhosphorIcon;
`;
}

function generateIconFile(icon) {
	return `${FILE_HEADER}import { ${icon.phosphorName} as Phosphor${icon.exportName} } from "@phosphor-icons/react";
import { createPhosphorIcon } from "./createPhosphorIcon";

export const ${icon.exportName} = createPhosphorIcon("${icon.exportName}", Phosphor${icon.exportName});
`;
}

function generateIndexFile(icons) {
	const exports = icons
		.map(icon => `export { ${icon.exportName} } from "./${icon.fileName}";`)
		.join('\n');

	return `${FILE_HEADER}${exports}

// Export the props type
export type { IconsProps } from "../types/iconTypes";
`;
}

function removeLegacyGeneratedIcons(icons) {
	const preserved = new Set(['index.ts', 'createPhosphorIcon.tsx', 'iconManifest.ts', 'README.md']);
	const expected = new Set(icons.map(icon => `${icon.fileName}.tsx`));

	if (!fs.existsSync(ICONS_DIR)) {
		return 0;
	}

	let removedCount = 0;

	for (const entry of fs.readdirSync(ICONS_DIR)) {
		const fullPath = path.join(ICONS_DIR, entry);
		const stats = fs.statSync(fullPath);

		if (!stats.isFile()) {
			continue;
		}

		if (preserved.has(entry)) {
			continue;
		}

		if (entry.endsWith('.tsx') && !expected.has(entry)) {
			fs.unlinkSync(fullPath);
			removedCount += 1;
		}
	}

	return removedCount;
}

async function main() {
	const icons = await loadManifest();

	validateIcons(icons);
	ensureDir(ICONS_DIR);

	let writtenCount = 0;

	if (writeFileIfChanged(path.join(ICONS_DIR, 'createPhosphorIcon.tsx'), generateHelperFile())) {
		writtenCount += 1;
	}

	for (const icon of icons) {
		const iconPath = path.join(ICONS_DIR, `${icon.fileName}.tsx`);
		if (writeFileIfChanged(iconPath, generateIconFile(icon))) {
			writtenCount += 1;
		}
	}

	if (writeFileIfChanged(path.join(ICONS_DIR, 'index.ts'), generateIndexFile(icons))) {
		writtenCount += 1;
	}

	const removedCount = removeLegacyGeneratedIcons(icons);

	process.stdout.write(
		`✅ Generated ${icons.length} icon wrappers, helper, and index (${writtenCount} file(s) written, ${removedCount} removed)\n`
	);
}

try {
	await main();
} catch (error) {
	process.stderr.write(`❌ Failed to generate icon wrappers: ${error.message}\n`);
	process.exit(1);
}
